### ISSUE TITLE
Error al consultar DNI

### ISSUE THREAD

**Issue by arce701** [giansalex/peru-consult#10]
Felicitaciones por su gran trabajo. 
El problema que tengo es que de un tiempo acá empecé a obtener el mensaje _"No se pudo crear imagen desde el captcha"_ lo cual impide consultar desde DNI.

> public function dni()
>     {
>         $dni = 'XXXXXXX';
>         $cs = new Dni();
>         $cs->setClient(new ContextClient());
>         $person = $cs->get($dni);
>         if ($person === false) {
>             echo $cs->getError();
>             exit();
>         }
>         echo json_encode($person);
>     }

**Comment by giansalex** [comment]
El servicio de reniec esta caido.
https://cel.reniec.gob.pe/valreg/valreg.do
ha ocurrido anteriormente, solo queda esperar.

**Comment by luisee** [comment]
Hola giansalex, la verdad es que hay una nueva web para el servicio de consulta de DNI
https://portaladminusuarios.reniec.gob.pe/validacionweb/index.html#no-back-button

Lo raro es que en http://quertium.com/UserPage/Reniec el servicio si funciona, que podría estar pasando?

**Comment by luisee** [comment]
https://cel.reniec.gob.pe/valreg/datos.do
Encontré esta web para sustituir a https://cel.reniec.gob.pe/valreg/valreg.do 
Pero de igual manera viene sin captcha, soluciones?

**Comment by giansalex** [comment]
La nueva consulta de reniec tiene recaptcha, no conozco método para superar esa barrera.
Acerca del ultimo que propones, obtiene la imagen de la misma fuente, es mas esa pagina parece que no es verdadera, puedes probar escribiendo cualquier cosa en **datos**, y sigue apareciendo la misma pagina
https://cel.reniec.gob.pe/valreg/giansalex.do

**Comment by luisee** [comment]
Entiendo, espero consigamos alguna solución :(

**Comment by giansalex** [comment]
@luisee , se utilizo el servicio de JNE, el cambio a realizar seria en el namespace: `Peru\Reniec\Dni` por `Peru\Jne\Dni`.
