### ISSUE TITLE
La API no responde al consultar DNI

### ISSUE THREAD

**Issue by OBSK** [giansalex/peru-consult#12]
Hola @giansalex, estuve haciendo pruebas, parece que la API de 

> peru-consult.herokuapp.com/public/api/v1

 no responde a solicitudes con DNI. 
Saludos

**Comment by giansalex** [comment]
Hola @OBSK , el problema es que el **scheme** seleccionado, deberia ser **HTTPS**, haré un ajuste para que se seleccione automaticamente.
