### ISSUE TITLE
Excepcion no controlada: Error 500 Web JNE

### ISSUE THREAD

**Issue by marcoadasilvaa** [giansalex/peru-consult#15]
Saludos!

Al enviar un DNI invalido al servido responde error 500 la web de JNE, este error no está controlado en el paquete

Ejemplo: DNI 12345678

![image](https://user-images.githubusercontent.com/4205973/57599922-e059e580-751d-11e9-88c4-cdb4142e432e.png)

**Comment by marcoadasilvaa** [comment]
Solución en la implementación en el Controller

![image](https://user-images.githubusercontent.com/4205973/57600195-b523c600-751e-11e9-8a5f-4a64eb07043e.png)

**Comment by giansalex** [comment]
Gracias @marcoadasilvaa por la observación, seria de gran ayuda si pudieras hacer un fork para aplicar ese cambio.

**Comment by giansalex** [comment]
Se realizó el cambio para evitar ese error, y retorne el mensaje genérico.
