### ISSUE TITLE
Problema al consultar DNI siguiendo el ejemplo de la documentacion

### ISSUE THREAD

**Issue by fabricciovt** [giansalex/peru-consult#17]
Hola, estoy tratando de consultar DNI, estoy usando Laravel, pero al tratar de realizar la consulta obtengo el siguiente error:

![image](https://user-images.githubusercontent.com/48162445/60404270-f757a400-9b6c-11e9-8e5b-440efcc6d906.png)

como puedo solucionarlo?
gracias

**Comment by giansalex** [comment]
Hola @fabricciovt, gracias por el aviso. 
El problema fue que la documentación que se esta mostrando es de una versión que aun no ha sido 
liberada. Pero ya fue corregida, puedes revisarla [aquí](https://giansalex.github.io/peru-consult/dni/).

**Comment by fabricciovt** [comment]
@giansalex gracias por la rápida respuesta, efectivamente ese era el problema.
Saludos
