### ISSUE TITLE
Respuesta "No se encontro el ruc"

### ISSUE THREAD

**Issue by sysarp** [giansalex/peru-consult#18]
Buen dia, a todo ruc que consulto me devuelve que "no se encontro el ruc"

http://localhost/api/v1/ruc/20550263948?token=abcxyz 

eh realizado un composer update por si habia nuevas actualizaciones y tengo el mismo resultado a que puede ser esto, ya que ha estado trabajando muy bien.

**Comment by giansalex** [comment]
Hola @sysarp, si hay un problema, pero es con cualquier ruc. La opción que se utiliza es por búsqueda por nombres en Sunat, y esta mostrando un error. Esperemos que sea temporal.

**Comment by sysarp** [comment]
Gracias por la respuesta,...

**Comment by itamaradin15** [comment]
Tengo el mismo error. como se puede solucionar?

**Comment by giansalex** [comment]
El problema sigue aun, tal vez pueda usarse http://www.sunat.gob.pe/cl-ti-itmrconsruc/FrameCriterioBusquedaMovil.jsp

**Comment by abelnexus** [comment]
Ojala vuelve a la normalidad :(

**Comment by mariodaviddelgado** [comment]
Hola q tal? aun sigue el inconveniente, estoy optando la medida de usar una pagina que me da como 300 consultas, entiendo que luego de eso me cobrará, ustedes que salida le estan dando?

**Comment by itamaradin15** [comment]
@mariodaviddelgado cual es ese servicio

**Comment by jkpulido** [comment]
He creado un pull request, cambiandole la url de consulta.
Lo he probado desde **peru-consult-api** y me está funcionando bien

https://github.com/giansalex/peru-consult/pull/19/files

Gracias @giansalex :D

 @itamaradin15 Si deseas algún servicio, algunos colegas y yo hemos creado una capa superior de consulta ruc y dni, por ahora está disponible de forma gratuita en https://www.apisperu.com/

Saludos.

**Comment by giansalex** [comment]
Gracias @jkpulido, lo intente probar hay algunos campos que no se retornan y otros que deben renombrarse, tendré que hacer algunos cambios adicionales

**Comment by mariodaviddelgado** [comment]
Hola como estas, proveedores software para clientes con el rubro de ventas itinerantes, quisiera saber los costos del servicio, escríbeme al correo mario.delgado@teayudo.pe<mailto:mario.delgado@teayudo.pe> x favor.

Saludos
950330576

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

________________________________
De: Itamar Garcia <notifications@github.com>
Enviado: Thursday, August 8, 2019 10:48:53 AM
Para: giansalex/peru-consult <peru-consult@noreply.github.com>
Cc: Mario Delgado <mariodavid.delgado@outlook.com>; Mention <mention@noreply.github.com>
Asunto: Re: [giansalex/peru-consult] Respuesta "No se encontro el ruc" (#18)


@mariodaviddelgado<https://github.com/mariodaviddelgado> cual es ese servicio

**Comment by giansalex** [comment]
La consulta de ruc esta activa de nuevo 😄 
> El cambio de la otra url estará pendiente de implementar para que sirve como alternativa, ante una posible caida de la url que se usa actualmente
