### ISSUE TITLE
Error consulting DNI number JNE

### ISSUE THREAD

**Issue by zMiguelk3** [giansalex/peru-consult#22]
Apparently the Query Address

`http://aplicaciones007.jne.gob.pe/srop_publico/Consulta/Afiliado/GetNombresCiudadano?DNI` 

it's not working, a captcha was apparently added,

Does anyone else have trouble consulting this service?

**Comment by giansalex** [comment]
Hola @zMiguelk3, si tendremos que buscar otra fuente para obtener el DNI, una propuesta era usar la consulta de SUNAT que incluye la busqueda por DNI, aunque solo seria para los que tienen ruc 😕

**Comment by zMiguelk3** [comment]
@giansalex Sí, estaba buscando opciones, está URL es solo para ESSALUD verdad?

` https://ww1.essalud.gob.pe/sisep/postulante/postulante/postulante_obtenerDatosPostulante.htm`

**Comment by giansalex** [comment]
si, pero creo que encontre una forma de seguir usando el mismo servicio
```
curl 'http://aplicaciones007.jne.gob.pe/srop_publico/Consulta/api/AfiliadoApi/GetNombresCiudadano' -H 'RequestVerificationToken: 30OB7qfO2MmL2Kcr1z4S0ttQcQpxH9pDUlZnkJPVgUhZOGBuSbGU4qM83JcSu7DZpZw-IIIfaDZgZ4vDbwE5-L9EPoBIHOOC1aSPi4FS_Sc1:clDOiaq7mKcLTK9YBVGt2R3spEU8LhtXEe_n5VG5VLPfG9UkAQfjL_WT9ZDmCCqtJypoTD26ikncynlMn8fPz_F_Y88WFufli38cUM-24PE1' -H 'Content-Type: application/json;chartset=utf-8' --data-binary '{"CODDNI":"46658592"}' ;
```

Ahora se envía y se recibe un json

**Comment by zMiguelk3** [comment]
@giansalex Bien, Funciona. Gracias

**Comment by giansalex** [comment]
@zMiguelk3 si lo llegas a implementar, seria genial si luego lo compartes en un pull request 😀

**Comment by GustavoFabianVergara** [comment]
@zMiguelk3 si funciona con el json, veré como lo integro y lo comparto

**Comment by giansalex** [comment]
Seria un gran aporte @GustavoFabianVergara 🎉

**Comment by jhenrygv** [comment]
> Hola @zMiguelk3, si tendremos que buscar otra fuente para obtener el DNI, una propuesta era usar la consulta de SUNAT que incluye la busqueda por DNI, aunque solo seria para los que tienen ruc

Hola Gian, encontré una fuente desde essalud: https://ww1.essalud.gob.pe/sisep/postulante/postulante/postulante_obtenerDatosPostulante.htm?strDni=47069487

Si se podría actualizar el repositorio sería genial :)

**Comment by giansalex** [comment]
Hola @jhenrygv, si se podría agregar como una fuente adicional.

**Comment by malban35** [comment]
Hola. Encontré un sitio que convierte código Curl a PHP: https://incarnate.github.io/curl-to-php/
Así quedo el código, lo probé y funciona bien:
`<?php
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'http://aplicaciones007.jne.gob.pe/srop_publico/Consulta/api/AfiliadoApi/GetNombresCiudadano');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"CODDNI\":\"46658592\"}");
curl_setopt($ch, CURLOPT_POST, 1);

$headers = array();
$headers[] = 'Requestverificationtoken: 30OB7qfO2MmL2Kcr1z4S0ttQcQpxH9pDUlZnkJPVgUhZOGBuSbGU4qM83JcSu7DZpZw-IIIfaDZgZ4vDbwE5-L9EPoBIHOOC1aSPi4FS_Sc1:clDOiaq7mKcLTK9YBVGt2R3spEU8LhtXEe_n5VG5VLPfG9UkAQfjL_WT9ZDmCCqtJypoTD26ikncynlMn8fPz_F_Y88WFufli38cUM-24PE1';
$headers[] = 'Content-Type: application/json;chartset=utf-8';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);

echo json_encode($result);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);
?>`

**Comment by elviss116** [comment]
> Hola. Encontré un sitio que convierte código Curl a PHP: https://incarnate.github.io/curl-to-php/
> Así quedo el código, lo probé y funciona bien:
> `<?php
> $ch = curl_init();
> 
> curl_setopt($ch, CURLOPT_URL, 'http://aplicaciones007.jne.gob.pe/srop_publico/Consulta/api/AfiliadoApi/GetNombresCiudadano');
> curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
> curl_setopt($ch, CURLOPT_POSTFIELDS, "{"CODDNI":"46658592"}");
> curl_setopt($ch, CURLOPT_POST, 1);
> 
> $headers = array();
> $headers[] = 'Requestverificationtoken: 30OB7qfO2MmL2Kcr1z4S0ttQcQpxH9pDUlZnkJPVgUhZOGBuSbGU4qM83JcSu7DZpZw-IIIfaDZgZ4vDbwE5-L9EPoBIHOOC1aSPi4FS_Sc1:clDOiaq7mKcLTK9YBVGt2R3spEU8LhtXEe_n5VG5VLPfG9UkAQfjL_WT9ZDmCCqtJypoTD26ikncynlMn8fPz_F_Y88WFufli38cUM-24PE1';
> $headers[] = 'Content-Type: application/json;chartset=utf-8';
> curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
> 
> $result = curl_exec($ch);
> 
> echo json_encode($result);
> if (curl_errno($ch)) {
> echo 'Error:' . curl_error($ch);
> }
> curl_close($ch);
> ?>`

hola, acabo de copiar todo el codigo a un archivo php y al ejecutarlo recibo error

<head>
	<title>Document Moved<\/title> <\/head>\n <body>
			<h1>Object Moved<\/h1>This document may be found <a
					HREF=\"https:\/\/aplicaciones007.jne.gob.pe\/srop_publico\">here <\/a> <\/body>"

**Comment by elviss116** [comment]
> @giansalex Bien, Funciona. Gracias

hola, como lo haria funcionar en postman?

**Comment by giansalex** [comment]
@elviss116 debe estar relacionado a este issue https://github.com/giansalex/peru-consult/issues/27#issuecomment-643559447, la url debe cambiarse a https

**Comment by mario125** [comment]
https://aplicaciones007.jne.gob.pe/srop_publico/Consulta/api/AfiliadoApi/GetNombresCiudadano

Error al consultar el número
