### ISSUE TITLE
Error al consultar DNI invalido

### ISSUE THREAD

**Issue by marcoadasilvaa** [giansalex/peru-consult#24]
PHP: 7.3
Versión: giansalex/peru-consult 4.1

Al ingresar un DNI invalido o no existente, no se maneja correctamente la excepción:

Ejemplo: 90305009 

![image](https://user-images.githubusercontent.com/4205973/67823409-04d85880-fa91-11e9-956b-ed72a8fe1478.png)

**Comment by EliuTimana** [comment]
Que extraño, cuando se ingresa un dni inválido la respuesta es esta 
```
{
    "data": "|||DNI no encontrado en Padrón Electoral ",
    "success": true,
    "mensaje": ""
}
```
y como ves, la propiedad `data` si existe.

**Comment by giansalex** [comment]
Hola @marcoadasilvaa, el error no esta relacionado con el dni invalido, sucede por ejemplo cuando se pierde la conexion a internet, o el servidor no responde.
Estoy aplicando una validación para evitar que salga esa excepción.

**Comment by giansalex** [comment]
Se aplico el cambio.
