### ISSUE TITLE
Uninitialized string offset: 7

### ISSUE THREAD

**Issue by alejosv** [giansalex/peru-consult#26]
Tengo un proyecto en donde utilizo la consulta DNI, eventualmente me esta emitiendo el siguiente error:

`/vendor/giansalex/peru-consult/src/Peru/Jne/DniParser.php in yii\web\ErrorHandler::handleError` el error se generó en una de las consultas utilizando el siguiente DNI: 9609865 
`Uninitialized string offset: 7` he indica que se generó en el siguiente archivo y línea

https://github.com/giansalex/peru-consult/blob/d9ead9e6b95058eac6273828f3ff8f38408d6733/src/Peru/Jne/DniParser.php#L31

**Comment by alejosv** [comment]
Esta excepción se disparó con los siguientes DNI:
7646742, 9156269, 9512670, 8177866, 7445834, 1332893, 7458143, 9609865

**Comment by alejosv** [comment]
Para más detalle: https://sentry.io/share/issue/a5dfa4ed888a43af9b9afd8f43a65a24/

**Comment by giansalex** [comment]
Hola @alejosv, el DNI tiene 8 dígitos, haré una actualización para evitar que salga ese error.

**Comment by alejosv** [comment]
El test no esta pasando y el marge a master no se esta haciendo :-/

**Comment by giansalex** [comment]
Hubo un problema en un servicio, pero ya se ejecutó.

**Comment by alejosv** [comment]
Recuerde que mientras no libere una minor version para composer el cambio no de va a ver reflejado ... gracias por este proyecto

**Comment by giansalex** [comment]
Dado que el error es poco probable que ocurra considerando que el nro de DNI debe tener 8 digitos, este cambio será incluido en una posterior versión.
