### ISSUE TITLE
ErrorException: Trying to get property 'data'

### ISSUE THREAD

**Issue by megasoft-dev** [giansalex/peru-consult#27]
Saludos mi estimado, tengo un problema al realizar las consultas el día de hoy:
Exactamente aquí:
**ErrorException: Trying to get property 'data' of non-object in file /home/vagrant/code/----/vendor/giansalex/peru-consult/src/Peru/Jne/Dni.php on line 59**

**Comment by anthonny2890** [comment]
Amigo yo prove cambiando http por https en la URL_CONSULT en el archivo DNI.php y funcionó denuevo, de todas maneras propuse este cambio al proyecto por este sitio.

**Comment by giansalex** [comment]
Esto había ocurrido antes #24

**Comment by giansalex** [comment]
> Amigo yo prove cambiando http por https en la URL_CONSULT en el archivo DNI.php y funcionó denuevo, de todas maneras propuse este cambio al proyecto por este sitio.

Hola @anthonny2890, esto es reciente o cuando tuviste ese problema?

**Comment by anthonny2890** [comment]
Hoy tuve ese problema tambien.

**Comment by giansalex** [comment]
Veo que en el ultimo [build](https://github.com/giansalex/peru-consult/runs/767506558#step:9:15), esta apareciendo ese error

**Comment by giansalex** [comment]
Con el cambio a `https` fue corregido, gracias @anthonny2890. 
He creado un release con ese cambio, versión `v4.1.1`

**Comment by elviss116** [comment]
le agrege la s y si funciono , una pregunta, la api de ESSALUD brindaba mas datos pero veo que ya lo dieron de baja o me parece?

**Comment by aherme-hv** [comment]
¡Houston tenemos problemas!, estimado amigo, nuevamente no hay respuesta al consultar a la reniec por intermedio de este servicio.
Gracias por el servicio!

**Comment by giansalex** [comment]
@aherme-hv puedes revisar aqui #29
