### ISSUE TITLE
Error al consultar DNI, devuelve null

### ISSUE THREAD

**Issue by jhuniors2111** [giansalex/peru-consult#29]

**Comment by giansalex** [comment]
Hola @jhuniors2111 , gracias por reportarlo, aparentemente el valor del token ya no funciona, se tendria que cambiar [aqui](https://github.com/giansalex/peru-consult/blob/master/src/Peru/Jne/Dni.php#L20).
Este ese el valor que use y funciona:
```php
private const REQUEST_TOKEN = 'Dmfiv1Unnsv8I9EoXEzbyQExSD8Q1UY7viyyf_347vRCfO-1xGFvDddaxDAlvm0cZ8XgAKTaWclVFnnsGgoy4aLlBGB5m-E8rGw_ymEcCig1:eq4At-H2zqgXPrPnoiDGFZH0Fdx5a-1UiyVaR4nQlCvYZzAhzmvWxLwkUk6-yORYrBBxEnoG5sm-Hkiyc91so6-nHHxIeLee5p700KE47Cw1';
```

**Comment by giansalex** [comment]
Actualice el token, ya esta funcionando, ademas agregue un nuevo campo para cambiar el token, si ocurre nuevamente el problema, no haya necesidad de actualizar la librería; seria de esta forma:
```php
$consult->setRequestToken('097n0wui1....4I6yIMF2xGS');

$consult->get($dni);
```

**Comment by giansalex** [comment]
Se genero un release (🇵🇪  `v4.1.2`),  puedes actualizar a la ultima versión

**Comment by cmr4b1t** [comment]
Hola como saber si el token va caducar y como tener un token personal?

**Comment by giansalex** [comment]
@cCarrot la probabilidad de que cambie el token puede ocurrir cuando se migra de servidores, y el tener un token propio no evitaría eso, es por ello que la librería mantiene un token general.

**Comment by elviss116** [comment]
hola, no esta funcionando actualmente, saben si ha cambiado el token ??

**Comment by washingtonaya** [comment]
Saludos. 
Al parecer el token ya cambio, por que para hoy ya no funciona. :'(

**Comment by elviss116** [comment]
> Saludos.
> Al parecer el token ya cambio, por que para hoy ya no funciona. :'(

yo lo tengo con curl y el error que obtengo es:

{
    "$id": "1",
    "Message": "No HTTP resource was found that matches the request URI 'https://aplicaciones007.jne.gob.pe/srop_publico/Consulta/api/AfiliadoApi/GetNombresCiudadano'."
}
