### ISSUE TITLE
No muestra datos

### ISSUE THREAD

**Issue by floriban** [giansalex/peru-consult#33]
En primer lugar felicitar el gran trabajo que han hecho, solo tengo un problema, cuando pruebo el codigo en local me funciona muy bien, pero cuando lo subo al servidor no me vota datos, haciendo var_dump a algunas variables resulta que aqui:

`$cs = $factory->create();
$cliente = $cs->get($documento);
var_dump($cliente);`

en local me sale todo un objeto, pero en el servidor me sale directamente NULL, derrpente a alguien le paso lo mismo, gracias de ante mano.

**Comment by giansalex** [comment]
La configuración alternativa es esta:

```php
use Peru\Http\ContextClient;
use Peru\Jne\{Dni, DniParser};


$client = new ContextClient();
$client->options = [
  'http' => [
    'protocol_version' => 1.0,
    'user_agent' => null,
  ],
  'ssl' => [
    'verify_peer' => false,
    'verify_peer_name' => false,
  ],
];

$cs = new Dni($client, new DniParser());
```
