### ISSUE TITLE
no funciona el api

### ISSUE THREAD

**Issue by elviss116** [giansalex/peru-consult#34]
Hola, alguien sabe alguna forma de corregir el problema actual??
no hay respuesta del servidor, devuelve vacio.

este es mi codigo:

tengo y un codigo curl en php y 
esta es la respuesta que tengo

{
    "data": "||",
    "success": true,
    "mensaje": ""
}

**Comment by giansalex** [comment]
Hola, probablemente el DNI sea de un menor de edad.

**Comment by elviss116** [comment]
> Hola, probablemente el DNI sea de un menor de edad.

hola, no es de un menor de edad, es mi dni, tengo el siguiente codigo .

No se si estoy desactualizado pero la ultima vez que lo corregi estuve en la issue 29 , en la cual cambio el token del api del JNE

`<?php
header('Content-Type: application/json; Charset=UTF-8');
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
if($_SERVER['REQUEST_METHOD'] == 'POST'){
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    
    $dni = $_POST['dni'];
    
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'https://aplicaciones007.jne.gob.pe/srop_publico/Consulta/api/AfiliadoApi/GetNombresCiudadano');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"CODDNI\":\"$dni\"}");

    $headers = array();
    //$headers[] = 'Requestverificationtoken: 30OB7qfO2MmL2Kcr1z4S0ttQcQpxH9pDUlZnkJPVgUhZOGBuSbGU4qM83JcSu7DZpZw-IIIfaDZgZ4vDbwE5-L9EPoBIHOOC1aSPi4FS_Sc1:clDOiaq7mKcLTK9YBVGt2R3spEU8LhtXEe_n5VG5VLPfG9UkAQfjL_WT9ZDmCCqtJypoTD26ikncynlMn8fPz_F_Y88WFufli38cUM-24PE1';
    
    $headers[] = 'Requestverificationtoken: Dmfiv1Unnsv8I9EoXEzbyQExSD8Q1UY7viyyf_347vRCfO-1xGFvDddaxDAlvm0cZ8XgAKTaWclVFnnsGgoy4aLlBGB5m-E8rGw_ymEcCig1:eq4At-H2zqgXPrPnoiDGFZH0Fdx5a-1UiyVaR4nQlCvYZzAhzmvWxLwkUk6-yORYrBBxEnoG5sm-Hkiyc91so6-nHHxIeLee5p700KE47Cw1';
    
    $headers[] = 'Content-Type: application/json;chartset=utf-8';
    $headers[] = 'Accept: application/json';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    
    print_r($result);

}
curl_close($ch);
`

**Comment by giansalex** [comment]
@elviss116 probé el fragmento que enviaste y si devolvio datos, puedes probar con otro DNI y ver si funciona.

**Comment by elviss116** [comment]
> @elviss116 probé el fragmento que enviaste y si devolvio datos, puedes probar con otro DNI y ver si funciona.

por ejemplo he probado con el 47788150 y no funciona, me devuelve este formato vacio: 

`{
    "data": "||",
    "success": true,
    "mensaje": ""
}`

**Comment by giansalex** [comment]
@elviss116 si funciona en mi maquina: 

![image](https://user-images.githubusercontent.com/14926587/99273766-75b2f580-27f7-11eb-90e4-d9962134c10e.png)

**Comment by elviss116** [comment]
> @elviss116 si funciona en mi maquina:
> 
> ![image](https://user-images.githubusercontent.com/14926587/99273766-75b2f580-27f7-11eb-90e4-d9962134c10e.png)

listo, ya esta , estaba enviando mal la peticion, cierro

**Comment by elviss116** [comment]
hola, actualmente esta caido el api, no hay respuesta, abro un nuevo issue?
