### ISSUE TITLE
error consulta ruc

### ISSUE THREAD

**Issue by edwinmacalopu** [giansalex/peru-consult#40]
retorna error la consulta ruc, url ramdon ahora esta bloqueado 

![image](https://user-images.githubusercontent.com/15043775/118160793-60a0d300-b3e4-11eb-9285-6bd037b8c35c.png)

**Comment by giansalex** [comment]
Una solución alternativa, es obtener el valor `numRnd` de esta pagina https://e-consultaruc.sunat.gob.pe/cl-ti-itmrconsruc/jcrS00Alias?accion=consPorRazonSoc&razSoc=

**Comment by alexsoft12** [comment]
Se refire este
![image](https://user-images.githubusercontent.com/15861110/118199482-da52b400-b418-11eb-889e-9846362568f4.png)

**Comment by edwinmacalopu** [comment]
> Se refire este
> ![image](https://user-images.githubusercontent.com/15861110/118199482-da52b400-b418-11eb-889e-9846362568f4.png)

claro pero ese numRnd lo obtienes en el html del link que compartio giansalex  
![image](https://user-images.githubusercontent.com/15043775/118199846-8bf1e500-b419-11eb-8f8c-1b47cc614526.png)

**Comment by giansalex** [comment]
~@edwinmacalopu , @alexsoft12  He liberado una versión de prueba.~
```
composer require giansalex/peru-consult:^4.2.2-BETA.1
```

**Comment by alexsoft12** [comment]
Excelente amigo @giansalex
Gracias..!

![image](https://user-images.githubusercontent.com/15861110/118205861-f5c4bb80-b426-11eb-9e60-2fc7305beca9.png)

**Comment by edwinmacalopu** [comment]
@giansalex  puedes implementarlo en peru-consult-api?

**Comment by giansalex** [comment]
@edwinmacalopu mañana se estará actualizando.

**Comment by giansalex** [comment]
@edwinmacalopu ya se implementó en peru-consult-api .

**Comment by leog1992** [comment]
![imagen](https://user-images.githubusercontent.com/8444234/118314682-168a2100-b4ba-11eb-903f-a6361c7b0c9a.png)

**Comment by leog1992** [comment]
he actualizado a la ultima version pero nada, lo que hice fue reemplazar manualmente el repositorio por el BETA
y funciona

**Comment by giansalex** [comment]
@leog1992 si, no es considerada la ultima versión por composer, se tiene que usar el comando de arriba. Todavía no se colocará como ultima versión hasta el lunes, si es que se vuelve a activar la anterior url.

**Comment by leog1992** [comment]
porque sale asi cuando quiero reinstalar?

 In DefinitionErrorExceptionPass.php line 54:
!!   Cannot autowire service "Peru\Sunat\RucParser": argument "$parser" of method "__construct()" references interface "Peru\Sunat\HtmlParserInterface" but no such service exists. You should maybe alias this interface to the existing "Peru\Sunat\HtmlParser" service.

**Comment by ycamposde** [comment]
En mi caso aquí sabe $table->length == 0 como pueden visualizar en la imagen 
![Sin título](https://user-images.githubusercontent.com/35236102/118330329-3bd45a80-b4cd-11eb-8609-5acb3fdadd9a.png)

![image](https://user-images.githubusercontent.com/35236102/118330478-5f97a080-b4cd-11eb-8b07-a5e5f3af1b60.png)

**Comment by leog1992** [comment]
composer require giansalex/peru-consult:4.4.2-BETA.1

**Comment by giansalex** [comment]
@leog1992 si usas [peru-consult-api](https://github.com/giansalex/peru-consult-api), deberías descargar la ultima versión del repositorio, esos parámetros están preconfigurados.

**Comment by giansalex** [comment]
@leog1992 si usas [peru-consult-api](https://github.com/giansalex/peru-consult-api), deberías descargar la ultima versión del repositorio, esos parámetros están preconfigurados.

**Comment by giansalex** [comment]
Se puede obtener la versión final, actualizando el paquete.
```
composer update giansalex/peru-consult
```
o para los que usaron la versión BETA anterior.
```
composer require giansalex/peru-consult:^4.2.2
```

**Comment by dsbhmp0610** [comment]
Saludos Gian, he bajado la ultima versión, y aun sigo sin obtener los datos del RUC.

**Comment by giansalex** [comment]
@dsbhmp0610 lo acabo de probar y esta funcionando.

**Comment by dsbhmp0610** [comment]
Lo he bajado por composer y también por el github, revisé los cambios que hiciste en el archivo Ruc.php y Endpoints.php, lo he probado en mi localhost y en mi servidor, y nada... no sé que estoy haciendo mal.

**Comment by ycamposde** [comment]
Gracias si me funciona 

composer require giansalex/peru-consult:^4.2.2

**Comment by dsbhmp0610** [comment]
![image](https://user-images.githubusercontent.com/8405245/118658323-e55b6a80-b7b1-11eb-8909-651ae3177e2b.png)

**Comment by leog1992** [comment]
asi no funciona
composer require giansalex/peru-consult:^4.2.2
error con el simbolo ^

prueba; composer require giansalex/peru-consult:4.4.2-BETA.1
o composer require giansalex/peru-consult
o composer update giansalex/peru-consult
