### ISSUE TITLE
Error consulta Ruc

### ISSUE THREAD

**Issue by edwinmacalopu** [giansalex/peru-consult#43]
el link para obtener el random esta cerrado : https://e-consultaruc.sunat.gob.pe/cl-ti-itmrconsruc/jcrS00Alias?accion=consPorRazonSoc&razSoc=

ahora se puede obtener el random con el mismo link pero poniendo una razón social : https://e-consultaruc.sunat.gob.pe/cl-ti-itmrconsruc/jcrS00Alias?accion=consPorRazonSoc&razSoc=BBVA

**Comment by leog1992** [comment]
exacto hay que modificar en EndPoints.php

**Comment by luistimana** [comment]
Excelente

**Comment by giansalex** [comment]
Otra posibilidad que había visto desde la anterior corrección, es reducir el tamaño de la respuesta.
- Consulta `razSoc=BBVA`, size `37kb`
- Consulta `razSoc=BVA%20FOODS`, size `16kb` , (`-56%`)

En cuanto al tiempo de respuesta, según el navegador son similares, entonces para la actualización del repo se estará utilizando la segunda opción: https://e-consultaruc.sunat.gob.pe/cl-ti-itmrconsruc/jcrS00Alias?accion=consPorRazonSoc&razSoc=BVA%20FOODS

**Comment by giansalex** [comment]
Ya se puede actualizar a la última versión.
```
composer update giansalex/peru-consult
```
