### ISSUE TITLE
Problema al obtener datos de la sunat

### ISSUE THREAD

**Issue by BryanCardiet** [giansalex/peru-consult#46]
Al parecer sunat cerro el portal desde el cual se realizaban las consultas 
https://e-consultaruc.sunat.gob.pe/cl-ti-itmrconsruc/jcrS00Alias?accion=consPorRazonSoc&razSoc=BVA%20FOODS
ahora muestra mensaje de acceso denegado y parece que iniciaron un servicio para descargar la información de los ruc que se suministren al sistema.

https://e-consultaruc.sunat.gob.pe/cl-ti-itmrconsmulruc/jrmS00Alias
alguien tendrá alguna solución? muchas gracias.

**Comment by giansalex** [comment]
Parece que fue temporal, lo acabo de comprobar y esta funcionando.
