### ISSUE TITLE
Consulta RUC: NO SE ENCUENTRA EL URL RAMDOM 

### ISSUE THREAD

**Issue by luistimana** [giansalex/peru-consult#47]
Al parecer ya no se encuentra este url porque al buscar un N° de RUC no trae los datos
https://e-consultaruc.sunat.gob.pe/cl-ti-itmrconsruc/jcrS00Alias?accion=consPorRazonSoc&razSoc=BBVA
ese link debería traer los datos de bbva para tomarlos como ramdom, pero **me lleva al index de la consulta ruc, por tal motivo no hace la búsqueda de los datos RUC,** agradecería tu ayuda amigo.
@giansalex

**Comment by edwinmacalopu** [comment]
se puede sacar el random de aquí : https://e-consultaruc.sunat.gob.pe/cl-ti-itmrconsmulruc/captcha?accion=random , pero al parecer ya no funciona la combinación de https://e-consultaruc.sunat.gob.pe/cl-ti-itmrconsruc/jcrS00Alias?accion=consPorRuc&razSoc&nroRuc=10294891845&numRnd=1196953888 puedes confirmar @giansalex

**Comment by luistimana** [comment]
Alguna novedad?

**Comment by guto80** [comment]
sin novedades :S

**Comment by edwinmacalopu** [comment]
alguna actualización?

**Comment by giansalex** [comment]
@edwinmacalopu ahora se tiene que enviar vía `POST`, pero con el random del otro link no esta funcionando.

**Comment by edwinmacalopu** [comment]
otra alternativa que encontre es usar la consulta ruc masiva ,pero en este caso hay que descargar un archivo zip, y leer la segunda linea que trae los datos del ruc consultado la secuencia seria asi :

1. llamar al numero random https://e-consultaruc.sunat.gob.pe/cl-ti-itmrconsmulruc/captcha?accion=random 
2. ponerlo en el siguiente link https://e-consultaruc.sunat.gob.pe/cl-ti-itmrconsmulruc/jrmS00Alias?accion=consManual&txtRuc&selRuc=20554488090&random=-467862007
3. esa consulta dentro del html esta el link para descargar el zip que contiene un txt con los datos del ruc consultado
![image](https://user-images.githubusercontent.com/15043775/123311053-53e7c280-d4ec-11eb-9722-d5b68e2142c1.png)
4. el txt contiene los datos del ruc consultado en la segunda linea 
![image](https://user-images.githubusercontent.com/15043775/123311269-96110400-d4ec-11eb-9799-83dc1429c88f.png)

**Comment by giansalex** [comment]
@edwinmacalopu el problema es que no contiene toda la información que esta disponible en la consulta individual. Estuve revisando y vi que se puede usar el mismo codigo random en multiples consultas, despues de la primera consulta por el navegador, aun estaré revisando si hay alguna salida por allí.

**Comment by giansalex** [comment]
Al parecer ambos métodos cambiaron de GET a POST,  pero surge un problema con la llamada usando `file_get_contents` y tendria que cambiarse a `curl`, asi quedaria el metodo  `Ruc::get`

```php
    public function get(string $ruc): ?Company
    {
        $this->client->get(Endpoints::CONSULT);
        $htmlRandom = $this->client->post(Endpoints::CONSULT, [
            'accion' => 'consPorRazonSoc',
            'razSoc' => 'BVA FOODS',
        ], ['Connection' => 'keep-alive', 'Accept' => '*/*']);

        $random = $this->getRandom($htmlRandom);

        $html = $this->client->post(Endpoints::CONSULT, [
            'accion' => 'consPorRuc',
            'nroRuc' => $ruc,
            'numRnd' => $random,
            'actReturn' => '1',
            'modo' => '1',
        ]);
        return $html === false ? null : $this->parser->parse($html);
   }
```

**Comment by giansalex** [comment]
Pueden obtener la versión que funciona, con este comando.
```bash
 composer require giansalex/peru-consult:^v4.4.4-BETA.2
 ```

**Comment by GianmarcoCV** [comment]
> Pueden obtener la versión que funciona, con este comando.
> 
> ```shell
>  composer require giansalex/peru-consult:^v4.4.4-BETA.2
> ```

Gracias @giansalex  Te invité un café vía Yape.

**Comment by edwinmacalopu** [comment]
@giansalex ya se puede usar en peru-consult-api?

**Comment by giansalex** [comment]
La versión final se encuentra en `v4.4.4`, que ahora requiere la extensión `curl `.

```
 composer update giansalex/peru-consult
```
