### ISSUE TITLE
Error consultar DNI el token ya no funciona 

### ISSUE THREAD

**Issue by washingtonaya** [giansalex/peru-consult#52]
Saludos.
Al parecer el token ya no funciona, alguien puede sacarme de dudas, Gracias !!

**Comment by Recursero** [comment]
Hola. Creo que el problema es el endpoint del JNE. En mi sistema hacia la consulta y hoy me he percatado que está fallando.

**Comment by washingtonaya** [comment]
> Hola. Creo que el problema es el endpoint del JNE. En mi sistema hacia la consulta y hoy me he percatado que está fallando.

Pudiste resolver estimado ?

**Comment by edwinmacalopu** [comment]
le agregaron recaptcha a la consulta

**Comment by elviss116** [comment]
> le agregaron recaptcha a la consulta

entonces ya murio definitivamente el api ?

**Comment by washingtonaya** [comment]
Al parecer que si, se tendrá que buscar otra fuente ..

> > le agregaron recaptcha a la consulta
> 
> entonces ya murio definitivamente el api ?

**Comment by lecano** [comment]
Se puede intentar hacer scraping a las siguientes urls:

https://app1.susalud.gob.pe/registro/ (devuelve un solo string)
http://app.sis.gob.pe/SisConsultaEnLinea/Consulta/frmResultadoEnLinea.aspx (devuelve nombres y apellidos separados)

Enviar formularios es simple con goutte o similares pero no puedo con el captcha, estoy intentando con imagemagick y tesseract y solo tengo un 40% de éxito al hacer ocr de imagen a texto. Haber si alguien mas tiene otra posible solución o la config ideal para imagemagick.

**Comment by washingtonaya** [comment]
Encontré esta fuente y los datos devuelve en JSON 
estaba haciendo unas pruebas con cURL y anda muy bien 
La cuestión es integrarlo en el peru-consult-api  @giansalex  
curl -X POST https://ww1.sunat.gob.pe/ol-ti-itatencionf5030/registro/solicitante?tipDocu=1&numDocu=12345678 
-H "Content-Type: application/json" 
-H "Content-Length: 0"
`{
    "apeMatSoli": "SOSO",
    "apePatSoli": "CALDERON",
    "nombreSoli": "JHON"
}`

**Comment by elviss116** [comment]
> Encontré esta fuente y los datos devuelve en JSON estaba haciendo unas pruebas con cURL y anda muy bien La cuestión es integrarlo en el peru-consult-api @giansalex curl -X POST https://ww1.sunat.gob.pe/ol-ti-itatencionf5030/registro/solicitante?tipDocu=1&numDocu=12345678 -H "Content-Type: application/json" -H "Content-Length: 0" `{ "apeMatSoli": "SOSO", "apePatSoli": "CALDERON", "nombreSoli": "JHON" }`

va genial, muchas gracias

**Comment by giansalex** [comment]
@washingtonaya gracias, hice el cambio ~y lo puse en una versión pre-release~, pueden probar actualizando con este comando:
```
 composer require giansalex/peru-consult
```

**Comment by MarcoRuiz** [comment]
La nueva versión 4.5.0-BETA.2 si funciona para consultar el dni, sin embargo con ruc no me funciona.
