### ISSUE TITLE
Dockerizar Servicio

### ISSUE THREAD

**Issue by max-dicson-cf** [giansalex/peru-consult#62]
Hola, sería bastante interesante que el servicio podamos obtenerlo desde dockerhub así como se encontraba la versión anterior.
De igual forma este cambio es bastante importante.

Gracias!

**Comment by giansalex** [comment]
@max-dicson-cf hace un tiempo docker hub dejo de publicar la imagen automaticamente, pero ahora ya esta publicada la ultima version.
