### ISSUE TITLE
No hay datos de respuesta a las solicitudes con DNI

### ISSUE THREAD

**Issue by arce701** [giansalex/peru-consult#63]
Cuando se hace una consulta se envia y responde, pero sin datos de respuesta, ya probé con varios DNIs y no funciona, las consultas al RUC si funcionan con normalidad.

**Comment by waytecperu** [comment]
hola yo tambien presente este problema, pero al no encontrar solución en la web, evalué  yo mismo la raíz del problema,  y es que el edpoint a cambiado  los parámetros de la url. entra a la siguiente ruta

vendor/giansalex/peru-consult/src/Peru/Jne/Endpoints.php

en mi caso esta instalado a través de vendor en cpanel, y esa es la ruta, luego abres ese archivo y editas la url.
**URLANTIGUA:** https://ww1.sunat.gob.pe/ol-ti-itatencionf5030/registro/solicitante?tipDocu=1&numDocu=%s

**URLACTUALIZADA:** https://ww1.sunat.gob.pe/ol-ti-itatencionf5030/registro/solicitante?tipDocu=1&numDocu=%s&tipPers=1

solo con ese cambio se arregla el tema de búsqueda por DNI. Espero te sirva saludos.

**Comment by arce701** [comment]
La solución propuesta funciona, solo queda esperar la actualización del paquete.
