### ISSUE TITLE
No funciona la consulta del DNI

### ISSUE THREAD

**Issue by MarcoRuiz** [giansalex/peru-consult#67]
al hacer la consulta, devuelve Not Found

**Comment by gersonponce** [comment]
Cambiaron el formulario de la sunat y le pusieron recaptcha, ¿alguna otra URL?

**Comment by yersey20037** [comment]
a mi tampoco me funciona. Alguna solución?

**Comment by Recursero** [comment]
Hola a todos. Tengo el mismo problema. Se tiene que modificar algo en el código?

**Comment by arce701** [comment]
hola, alguien ya descubrió como solucionarlo

**Comment by giansalex** [comment]
ya pude revisarlo

**Comment by giansalex** [comment]
pueden actualizar el paquete
```
composer update giansalex/peru-consult
```
