### ISSUE TITLE
Reniec DNI - Down

### ISSUE THREAD

**Issue by giansalex** [giansalex/peru-consult#7]
https://cel.reniec.gob.pe/valreg/valreg.do

**Comment by EliuTimana** [comment]
¿Existe alguna solución para el problema del servicio de la RENIEC?, ¿algún endpoint distinto en el que se puedea hacer la consulta?, esta librería es muy buena, sería una pena que quede obsoleta.

**Comment by giansalex** [comment]
es el único servico publico de Reniec que he visto, les envié un correo, y no saben cuando volverá estar activo. Si conoces algún servicio que retorne esa información se podría considerar.

**Comment by EliuTimana** [comment]
Provisionalmente se puede usar el servicio de la SUNAT, que permite obtener los nombres, aunque juntos, de las personas naturales, se perdería la separacion de nombres apellidos, porque el código de verificación está presente en el RUC que también devuelve.

**Comment by giansalex** [comment]
Si, podría ser.
![image](https://user-images.githubusercontent.com/14926587/41075860-40c03ba0-69d4-11e8-8d46-b5e0c6a7c4e9.png)

**Comment by EliuTimana** [comment]
He estado probando y me he dado cuenta que solo devuelve aquellos que están registrados en la SUNAT, no todos como la RENIEC; habrá que pensarlo o esperar a que el servicio vuelva en el mejor de los casos.

**Comment by giansalex** [comment]
Si, es desconcertante no saber cuando volverá estar activo.

**Comment by giansalex** [comment]
Finalmente esta disponible el nuevo link de [consulta de DNI](https://portaladminusuarios.reniec.gob.pe/validacionweb/index.html), pero lamentablemente ahora maneja un captcha mas seguro, [Recaptcha](https://www.google.com/recaptcha). No conozco algún método que pueda superar esa barrera. :pensive:
De tal modo la opción de consulta de DNI quedará **OBSOLETO**

**Comment by EliuTimana** [comment]
El servicio de  consulta de DNI de [RENIEC](https://cel.reniec.gob.pe/valreg/valreg.do), ahora ya está disponible, y esta librería aún funciona. :smiley:

**Comment by giansalex** [comment]
Y yo ya lo había quitado 😢.

**Comment by giansalex** [comment]
Ya esta activo, de nuevo.

**Comment by EliuTimana** [comment]
Servicio de RENIEC caído nuevamente. :rage:

**Comment by caledomper** [comment]
Hola, y si usas el servicio del padron del jurado nacional de elecciones?  
http://aplicaciones007.jne.gob.pe/srop_publico/Consulta/Afiliado/GetNombresCiudadano?DNI=71092490

**Comment by giansalex** [comment]
Hola @caledomper, gracias por el aporte, los cambios se aplicaron en https://github.com/giansalex/peru-consult/pull/11

**Comment by j4444333221** [comment]
Encontré un servicio https://serviciosportal.reniec.gob.pe/dniBioFacial/api/getAdditionalInformation

pueden obtener fotos mediante post

demo: https://apitester.com/shared/checks/303d81bfc1bf47028f90f1843d4435f2

obtiene la foto en base64

el servicio esta dentro de https://play.google.com/store/apps/details?id=pe.gob.reniec.dnibioface (decompilen)

**Comment by giansalex** [comment]
Hola, si funciona!, alguna vez encontré un servicio parecido pero además retornaba la información completa que aparece en el DNI, talvez este tenga la opción?.  Cuando tenga el ordenador a la mano revisaré ese apk, gracias!.

**Comment by DeveloperRafael1996** [comment]
Parece que nuevamente cayo el servicio para consultar DNI, habra una forma de como corregir esa problemas

**Comment by giansalex** [comment]
Hola @DeveloperRafael1996 , se encontro otra url para obtener la informacion https://github.com/giansalex/peru-consult/issues/22
